apiVersion: apps/v1
kind: Deployment
metadata:
   name: blockchain-deployment
   namespace: default
spec:
   replicas: 1
   selector:
      matchLabels:
         bb: web
   template:
      metadata:
         labels:
            bb: web
      spec:
         containers:
            -  name: blockchain-container
               image: blockchain
               imagePullPolicy: Never
               readinessProbe:
                  httpGet:
                     path: /
                     port: 3000
                  initialDelaySeconds: 2
                  periodSeconds: 1
                  timeoutSeconds: 1
                  successThreshold: 1
                  failureThreshold: 10
               resources:
                  limits:
                     memory: 200Mi
                  requests:
                     cpu: 200m
                     memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
   name: blockchain-service
   namespace: default
spec:
   type: NodePort
   selector:
      bb: web
   ports:
      - port: 3000
        targetPort: 3000
        nodePort: 30001